<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121001212631 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE postcards ADD sender_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE postcards ADD CONSTRAINT FK_90B24FEDF624B39D FOREIGN KEY (sender_id) REFERENCES fos_users (id)");
        $this->addSql("CREATE INDEX IDX_90B24FEDF624B39D ON postcards (sender_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE postcards DROP FOREIGN KEY FK_90B24FEDF624B39D");
        $this->addSql("DROP INDEX IDX_90B24FEDF624B39D ON postcards");
        $this->addSql("ALTER TABLE postcards DROP sender_id");
    }
}
